version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y docker.io

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 861276104826.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t newrepo .

      - echo Tagging the Docker image...
      - docker tag newrepo:latest 861276104826.dkr.ecr.eu-north-1.amazonaws.com/newrepo:latest

      - echo Pushing the Docker image to ECR...
      - docker push 861276104826.dkr.ecr.eu-north-1.amazonaws.com/newrepo:latest

      - echo Creating imagedefinitions.json...
      - |
        echo '[{"name":"newcontainer","imageUri":"861276104826.dkr.ecr.eu-north-1.amazonaws.com/newrepo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
